### ISSUE TITLE
Oomph installer: 'org.eclipse.xtext.sdk.feature.group [2.8.0,2.9.0)' but it could not be found

### ISSUE THREAD

**Issue by david-istvan** [IncQueryLabs/incquery-examples-cps#27]
ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:239)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:371)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:312)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:692)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:2755)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2700)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2681)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2620)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:523)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:608)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1427825398506
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: artificial_root 1.0.0.v1427825398506 requires 'org.eclipse.xtext.sdk.feature.group [2.8.0,2.9.0)' but it could not be found

**Comment by abelhegedus** [comment]
http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/ should be added to the repository list of Targlet and the P2 director task.

**Comment by abelhegedus** [comment]
In addition, the setup uses integration builds from EMF-IncQuery and VIATRA, so we have to wait till Friday before updating to Xtext 2.8
